language: java

jdk:
  - oraclejdk8
  - oraclejdk7

os:
  - linux

install:
  - mvn install

script:
  - mvn test
  - jdk_switcher use oraclejdk8
  - # do stuff with Java 8
  - jdk_switcher use oraclejdk7
  - # do stuff with Java 7
