notifications:
  irc:
    channels:
      - "chat.freenode.net#my-channel"
      - "chat.freenode.net#some-other-channel"
    on_success: [always|never|change] # default: always
    on_failure: [always|never|change] # default: alwayslanguage: java

jdk:
  - oraclejdk8
  - oraclejdk7

os:
  - linux

install:
  - mvn install

script:
  - mvn test
  - jdk_switcher use oraclejdk8
  - # do stuff with Java 8
  - jdk_switcher use oraclejdk7
  - # do stuff with Java 7
notifications:
  irc:
    channels:
      - "na.irc.esper.net#Q3-Bot"
      - "na.irc.esper.net#Q3-Dev"
    on_success: always # default: always
    on_failure: always # default: always
